[hanami]
blog_title = "My Weblog"
blog_description = "Yet another Hanami weblog."
blog_language = "en"
datadir = ""
url = ""
depth = 0
num_entries = 40
file_extension = "txt"
default_flavour = "html"
; not support show_future_entries right now
; also not support non utf-8
date_first_in_url = 0
