[hanami]
blog_title = "My Weblog"
blog_description = "A Weblog powered by Hanami."
blog_language = "en"
depth = 0
num_entries = 40
file_extension = "txt"
default_flavour = "html"
; not support show_future_entries right now
; also not support non utf-8
date_first_in_url = 0
plugin_dir = "plugins"
state_dir = "state"
entries_dir = "entries"
static_dir = "static"
host = "127.0.0.1"
port = 8999
; deliminated by space, relative to entries_dir
exclude = "/head.html /foot.html /story.html"
url = "example.com"
wrap_status_pages = 1
try_continue_on_plugin_exception = 0